---
name: Setup UV Environment
description: Install Python, cache uv environments, and sync dependencies for CI jobs.

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.13"

  uv-sync-flags:
    description: Flags passed to `uv sync`
    required: false
    default: "--all-extras"

  cache-key-prefix:
    description: Prefix used for caching uv environments
    required: false
    default: uv

  lockfile:
    description: Lockfile path hashed for cache invalidation
    required: false
    default: uv.lock

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

    - name: Cache uv environments
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles(inputs.lockfile) }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-

    - name: Sync dependencies
      shell: bash
      run: |
        set -eo pipefail
        uv sync ${{ inputs.uv-sync-flags }}
