# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# Explicit list of linters (descriptor names)
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - PYTHON_MYPY
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - JSON_JSONLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - REPOSITORY_SYFT

# Linters allowed to apply fixes (safe formatting)
APPLY_FIXES:
  - PYTHON_RUFF_FORMAT
  - MARKDOWN_MARKDOWNLINT

GITHUB_STATUS_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
SARIF_REPORTER: true

# General exclude regex (applies to all linters unless overridden)
FILTER_REGEX_EXCLUDE: (^docs/apis/|^src/birre/resources/apis/)

############################################
# Descriptor-specific configuration overrides
############################################

# Actionlint: restrict scope to GitHub workflow directory explicitly
ACTION_ACTIONLINT_FILTER_REGEX_INCLUDE: '^(\.github/workflows/.*\.ya?ml)$'

# Python Ruff (lint) uses pyproject.toml config; ensure formatting style is ruff
PYTHON_DEFAULT_STYLE: ruff
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
# Additional args (empty for now; ruff picks config from pyproject)
PYTHON_RUFF_CLI_LINT_MODE: project
PYTHON_RUFF_FILTER_REGEX_EXCLUDE: (^scripts/|^dist/|^\.venv/|^BiRRe\.egg-info/)

# Mypy strict typing config via pyproject
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_MYPY_ARGUMENTS: "--strict"
PYTHON_MYPY_CLI_LINT_MODE: project

# Enforce errors (override default disable)
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--fix"

# YAML Yamllint (optional config file forthcoming if needed)
YAML_YAMLLINT_ARGUMENTS: "--strict"

# JSON Jsonlint; syntax only; exclude large generated or SBOM artifacts
JSON_JSONLINT_ARGUMENTS: "--quiet"
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (^docs/apis/|^src/birre/resources/apis/)

# EditorConfig Checker (requires .editorconfig file at repo root)
EDITORCONFIG_EDITORCONFIG_CHECKER_ARGUMENTS: "-f github-actions"

# Syft SBOM generation (project mode). Produces CycloneDX + SPDX JSON artifacts.
REPOSITORY_SYFT_ARGUMENTS: "-o cyclonedx-json=artifacts/sbom-cyclonedx.json -o spdx-json=artifacts/sbom-spdx.json"

############################################
# Performance & Misc
############################################
SHOW_ELAPSED_TIME: true
# End of MegaLinter configuration
