# CodeCov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: auto          # compare to previous commit
        threshold: 1%         # allow 1% drop
        informational: false  # block if threshold exceeded
    patch:
      default:
        target: 70%           # new code should have 70%+ coverage
        threshold: 0%
        informational: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false      # always post comment
  require_base: false
  require_head: true
  hide_project_coverage: false  # show both project and patch coverage

github_checks:
  annotations: true  # show line-by-line coverage in GitHub PR

flags:
  offline-tests:
    paths:
      - src/birre/
  pr-validation:
    paths:
      - src/birre/

# Ignore test files and generated code from coverage
ignore:
  - "tests/"
  - "**/__pycache__/"
  - "**/*.pyc"
  - ".venv/"
  - "htmlcov/"
