[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BiRRe"
version = "3.0.0"
description = "Model Context Protocol server for BitSight security ratings"
authors = [{ name = "boecht" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp==2.12.4",
    "dynaconf",
    "python-dotenv",
    "httpx",
    "prance>=23.6.7",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.24.0",
    "pytest-mock>=3.12.0",
]

[project.urls]
repository = "https://github.com/boecht/birre"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[project.scripts]
birre = "server:main"
