from __future__ import annotations

CONFIG_BASENAME = "config"
DEFAULT_CONFIG_FILENAME = f"{CONFIG_BASENAME}.toml"
LOCAL_CONFIG_FILENAME = f"{CONFIG_BASENAME}.local.toml"

__all__ = [
    "CONFIG_BASENAME",
    "DEFAULT_CONFIG_FILENAME",
    "LOCAL_CONFIG_FILENAME",
]
